# psql -d db -U postgres
version: "3.9"
services:
  
  postgresql:
    image: postgres
    container_name: postgresql1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  
  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    # environment variables are not a list
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: userdb
      # root can log in from every host
      MYSQL_ROOT_HOST: '%'
    
    ports:
      - '3306:3306'
      